'use client';
import Link from 'next/link';
import { Panel, Badge, Progress } from '@/components/ui';
import { demoData } from '@/lib/data';
import { demoUsers } from '@/lib/auth';
import { useManagedUsers } from '@/lib/user-store';
import { Copy, ShieldCheck } from 'lucide-react';

export default function SettingsPage() {
  const { users } = useManagedUsers();
  const stats = [['Vendor records', demoData.vendors.length], ['Invoices', demoData.invoices.length], ['Matches', demoData.matching.length], ['Approvals', demoData.approvals.length], ['Payments', demoData.payments.length], ['Audit logs', demoData.audit.length], ['Managed users', users.length]];
  const rules = [
    ['L1 Team Lead', 'Up to INR 10,000', 'Attachment, GST/PAN, duplicate check'],
    ['L2 Account Manager', 'INR 10,001 to INR 1,00,000', 'PO/GRN variance, cost center, rework'],
    ['L3 Finance Head', 'Above INR 1,00,000', 'Final release, hold override, payment queue'],
  ];

  return <div className="space-y-6"><Panel title="Platform settings" subtitle="Workflow defaults, demo access, and ERP integration controls." action={<Link href="/users" className="rounded-lg border border-cyan-400/30 bg-cyan-400/10 px-3 py-2 text-xs font-semibold text-cyan-200 hover:bg-cyan-400/15">Manage users</Link>}><div className="flex flex-wrap gap-2"><Badge tone="cyan">GST validation enabled</Badge><Badge tone="emerald">Bank file generation on</Badge><Badge tone="violet">OCR confidence threshold 90%</Badge><Badge tone="amber">Match tolerance +/- 2%</Badge></div></Panel><section className="grid gap-4 xl:grid-cols-[0.9fr_1.1fr]"><Panel title="Default routing" subtitle="Amount-based approval thresholds"><div className="space-y-4">{rules.map(([role, range, duty], index) => <div key={role}><div className="mb-2 flex items-center justify-between gap-3 text-sm"><span className="text-slate-300">{role}</span><span className="text-slate-500">{range}</span></div><Progress value={[100, 70, 45][index]} /><div className="mt-2 text-xs text-slate-500">{duty}</div></div>)}</div></Panel><Panel title="Demo credentials" subtitle="Use these to switch persona during client walkthroughs."><div className="grid gap-3 md:grid-cols-2">{demoUsers.map((user) => <div key={user.email} className="rounded-lg border border-white/10 bg-slate-950/45 p-4"><div className="flex items-start justify-between gap-3"><div><div className="font-medium text-white">{user.role}</div><div className="mt-1 text-xs text-slate-500">{user.name}</div></div><Badge tone={user.accent}>{user.level}</Badge></div><div className="mt-3 rounded-lg border border-white/10 bg-black/20 p-3 font-mono text-[11px] leading-5 text-slate-400"><div>{user.email}</div><div>{user.password}</div></div><button className="mt-3 inline-flex items-center gap-2 text-xs text-cyan-300"><Copy size={13} /> Ready for login screen</button></div>)}</div></Panel></section><section className="grid gap-4 xl:grid-cols-2"><Panel title="Authority matrix" subtitle="What changes when users log in with different credentials."><div className="space-y-3">{demoUsers.map((user) => <div key={user.key} className="flex gap-3 rounded-lg border border-white/10 bg-slate-950/40 p-4"><ShieldCheck size={18} className="mt-0.5 shrink-0 text-cyan-300" /><div><div className="flex flex-wrap items-center gap-2"><span className="font-medium text-white">{user.role}</span><Badge tone={user.accent}>{user.level}</Badge></div><p className="mt-1 text-sm leading-6 text-slate-400">{user.scope}</p></div></div>)}</div></Panel><Panel title="Data volume" subtitle="Mock production scale bundled in the app"><div className="grid grid-cols-2 gap-3">{stats.map(([label, value]) => <div key={label as string} className="rounded-lg border border-white/10 bg-slate-950/40 p-4"><div className="text-xs uppercase tracking-[0.18em] text-slate-500">{label}</div><div className="mt-2 text-2xl font-semibold text-white">{String(value)}</div></div>)}</div></Panel></section></div>;
}
